---
extends: default

# For all rules
ignore: |
  .gitlab-ci-local
  node_modules/
  examples/docker-compose-nodejs/node_modules/
  examples/docker-swarm-php/vendor/
  MergeRequest-Pipelines.gitlab-ci.yml
  PHP.gitlab-ci.yml
  /.github/workflows/

rules:
  line-length: { max: 160 }
  braces: { min-spaces-inside: 1, max-spaces-inside: 1 }
