#!/bin/bash
set -e

mkdir -p /tmp/node-docker-home
chmod -R 777 /tmp/node-docker-home

docker run -it --rm \
    -u "$(id -u):$(id -g)" \
    -e NPM_HOME=/home/node/ \
    -v "/$PWD/:/app/" \
    -v "/tmp/node-docker-home/:/home/node/" \
    -w /app/ \
    node npm "$@"
