---
stages: [test, build, deploy]

# @Description Run Tests
test-job:
  stage: test
  script:
    - 'echo "Test something"'

build-job:
  stage: build
  needs: [test-job]
  allow_failure: true
  script:
    - 'echo "Build something"'

deploy-job:
  stage: deploy
  needs: [build-job]
  allow_failure: true
  script:
    - 'echo "Deploy something"'
  rules:
    - if: $ENVIRONMENT == "local"
      when: never
