#!/usr/bin/env tsx
/**
 * Generate embedded.ts from frontend source files
 *
 * This script:
 * 1. Reads CSS from styles/embedded.css
 * 2. Bundles app-bundle.ts with esbuild (IIFE format for browser)
 * 3. Generates embedded.ts with inlined assets
 *
 * Run with: npm run generate-embedded
 */

import * as fs from "fs";
import * as path from "path";
import * as esbuild from "esbuild";
import {fileURLToPath} from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const FRONTEND_DIR = path.join(__dirname, "../src/web/frontend");
const OUTPUT_FILE = path.join(FRONTEND_DIR, "embedded.ts");

/**
 * Escape special characters for embedding in a template literal
 */
function escapeTemplateString (str: string): string {
    return str
        .replace(/\\/g, "\\\\") // Escape backslashes first
        .replace(/`/g, "\\`") // Escape backticks
        .replace(/\$\{/g, "\\${"); // Escape template expressions
}

/**
 * Generate the HTML template with inlined CSS and JS
 */
function generateHTML (css: string, js: string): string {
    // Note: We use \${CHARTJS_LIB} in the template which will be preserved
    // because escapeTemplateString only escapes ${ not ${
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GitLab CI Local - Web UI</title>
    <style>
${css}
    </style>
</head>
<body>
    <header class="app-header">
        <div class="container">
            <div class="header-content">
                <h1 class="app-title">
                    <a href="#/" class="logo">GitLab CI Local</a>
                </h1>
                <nav class="app-nav">
                    <a href="#/" class="nav-link" id="nav-pipelines">Pipelines</a>
                    <a href="#/yaml" class="nav-link" id="nav-yaml">YAML</a>
                    <div class="status-indicator" id="nav-status">
                        <div class="status-dot idle"></div>
                        <span>Ready</span>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <main class="app-main">
        <div class="container">
            <div id="app-root">
                <div class="loading"><div class="spinner"></div></div>
            </div>
        </div>
    </main>
    <script>\${CHARTJS_LIB}</script>
    <script>
${js}
    </script>
</body>
</html>`;
}

/**
 * Generate the embedded.ts TypeScript file
 */
function generateEmbeddedTs (html: string): string {
    const escapedHtml = escapeTemplateString(html);

    return `// Auto-generated by scripts/generate-embedded.ts - DO NOT EDIT MANUALLY
// Source files:
//   - styles/embedded.css (CSS)
//   - app-bundle.ts (JavaScript)
// Regenerate with: npm run generate-embedded

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import {CHARTJS_LIB} from "./lib/chartjs.js";

export const INDEX_HTML = \`${escapedHtml}\`;
`;
}

async function main () {
    console.log("Generating embedded.ts...");

    // 1. Read CSS
    const cssPath = path.join(FRONTEND_DIR, "styles/embedded.css");
    if (!fs.existsSync(cssPath)) {
        throw new Error(`CSS file not found: ${cssPath}`);
    }
    const css = fs.readFileSync(cssPath, "utf-8");
    console.log(`  Read CSS: ${css.length} bytes from styles/embedded.css`);

    // 2. Bundle JavaScript with esbuild
    const entryPoint = path.join(FRONTEND_DIR, "app-bundle.ts");
    if (!fs.existsSync(entryPoint)) {
        throw new Error(`Entry point not found: ${entryPoint}`);
    }

    const result = await esbuild.build({
        entryPoints: [entryPoint],
        bundle: true,
        format: "iife", // Immediately Invoked Function Expression for browser
        target: "es2020", // Modern browsers (this is a dev tool)
        minify: false, // Keep readable for debugging
        write: false, // Return result instead of writing to disk
        platform: "browser", // Browser APIs available
        sourcemap: false, // No source maps for embedded
        treeShaking: true, // Remove unused code
        logLevel: "warning", // Only show warnings and errors
    });

    if (result.outputFiles.length === 0) {
        throw new Error("esbuild produced no output");
    }

    const bundledJs = result.outputFiles[0].text;
    console.log(`  Bundled JS: ${bundledJs.length} bytes from app-bundle.ts`);

    // 3. Generate embedded.ts
    const html = generateHTML(css, bundledJs);
    const embeddedTs = generateEmbeddedTs(html);

    // 4. Write output file
    fs.writeFileSync(OUTPUT_FILE, embeddedTs);

    const stats = fs.statSync(OUTPUT_FILE);
    console.log(`  Generated: ${OUTPUT_FILE}`);
    console.log(`  Total size: ${stats.size} bytes`);
    console.log("Done!");
}

main().catch((error) => {
    console.error("Failed to generate embedded.ts:", error.message);
    process.exit(1);
});
