// Auto-generated by scripts/generate-embedded.ts - DO NOT EDIT MANUALLY
// Source files:
//   - styles/embedded.css (CSS)
//   - app-bundle.ts (JavaScript)
// Regenerate with: npm run generate-embedded

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import {CHARTJS_LIB} from "./lib/chartjs.js";

export const INDEX_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GitLab CI Local - Web UI</title>
    <style>
/* ==========================================================================
   GitLab CI Local - Web UI Styles
   Source file for embedded.ts generation
   ========================================================================== */

/* ==========================================================================
   CSS Variables (Theme)
   ========================================================================== */

/* Default: Dark theme */
:root {
    --bg-color: #1a1a2e;
    --surface-color: #16213e;
    --text-color: #eee;
    --text-muted: #888;
    --accent-color: #f8c22fff;
    --success-color: #4caf50;
    --warning-color: #ff8800ff;
    --error-color: #f81515ff;
    --border-color: #2a2a4a;
    --hover-color: #1f2f4f;
    /* Log viewer colors */
    --log-bg: #0d1117;
    --log-text: #c9d1d9;
    --log-line-number: #484f58;
}

/* Light theme via system preference (when not manually overridden to dark) */
@media (prefers-color-scheme: light) {
    :root:not(.dark-theme) {
        --bg-color: #f5f5f5;
        --surface-color: #ffffff;
        --text-color: #1a1a1a;
        --text-muted: #666;
        --accent-color: #d4a017;
        --success-color: #2e7d32;
        --warning-color: #e65100;
        --error-color: #c62828;
        --border-color: #e0e0e0;
        --hover-color: #f0f0f0;
        --log-bg: #fafafa;
        --log-text: #24292f;
        --log-line-number: #8b949e;
    }
}

/* Force light theme via class (overrides system preference) */
:root.light-theme {
    --bg-color: #f5f5f5;
    --surface-color: #ffffff;
    --text-color: #1a1a1a;
    --text-muted: #666;
    --accent-color: #d4a017;
    --success-color: #2e7d32;
    --warning-color: #e65100;
    --error-color: #c62828;
    --border-color: #e0e0e0;
    --hover-color: #f0f0f0;
    --log-bg: #fafafa;
    --log-text: #24292f;
    --log-line-number: #8b949e;
}

/* Force dark theme via class (overrides system preference) */
:root.dark-theme {
    --bg-color: #1a1a2e;
    --surface-color: #16213e;
    --text-color: #eee;
    --text-muted: #888;
    --accent-color: #f8c22fff;
    --success-color: #4caf50;
    --warning-color: #ff8800ff;
    --error-color: #f81515ff;
    --border-color: #2a2a4a;
    --hover-color: #1f2f4f;
    --log-bg: #0d1117;
    --log-text: #c9d1d9;
    --log-line-number: #484f58;
}

/* ==========================================================================
   Base Styles & Reset
   ========================================================================== */
* { box-sizing: border-box; margin: 0; padding: 0; }
html { height: 100%; overflow: hidden; }
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg-color);
    color: var(--text-color);
    line-height: 1.5;
    height: 100%;
    display: flex;
    flex-direction: column;
    overflow: hidden;
}

/* ==========================================================================
   Layout
   ========================================================================== */
.container { max-width: 1200px; margin: 0 auto; padding: 0 1rem; }
.container.full-width { max-width: none; padding-right: 0; }

/* Header */
.app-header { background: var(--surface-color); border-bottom: 1px solid var(--border-color); padding: 1rem 0; flex-shrink: 0; }
.header-content { display: flex; justify-content: space-between; align-items: center; }
.app-title { font-size: 1.25rem; font-weight: 600; }
.logo { color: var(--text-color); text-decoration: none; }
.logo:hover { opacity: 0.8; }

/* Navigation */
.app-nav { display: flex; gap: 1rem; }
.nav-link { color: var(--text-muted); text-decoration: none; padding: 0.5rem 1rem; border-radius: 4px; transition: all 0.2s; }
.nav-link:hover { color: var(--text-color); background: var(--hover-color); }
.nav-link.active { color: var(--accent-color); background: var(--hover-color); }

/* Main Content */
.app-main { padding: 2rem 0; flex: 1; overflow-y: auto; }

/* ==========================================================================
   Cards
   ========================================================================== */
.card { background: var(--surface-color); border-radius: 8px; border: 1px solid var(--border-color); margin-bottom: 1rem; overflow: hidden; }
.card-header { padding: 1rem; border-bottom: 1px solid var(--border-color); display: flex; justify-content: space-between; align-items: center; }
.card-body { padding: 1rem; }

/* ==========================================================================
   Badges
   ========================================================================== */
.badge { display: inline-block; padding: 0.25rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
.badge-success { background: var(--success-color); color: white; }
.badge-warning { background: var(--warning-color); color: black; }
.badge-error { background: var(--error-color); color: white; }
.badge-running { background: var(--accent-color); color: white; animation: pulse 1.5s infinite; }
.badge-pending { background: var(--text-muted); color: white; }

/* ==========================================================================
   Animations
   ========================================================================== */
@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.7; } }
@keyframes spin { to { transform: rotate(360deg); } }
@keyframes pulse-ring { 0%, 100% { box-shadow: 0 0 0 0 rgba(233, 69, 96, 0.4); } 50% { box-shadow: 0 0 0 8px rgba(233, 69, 96, 0); } }

/* ==========================================================================
   Pipeline List
   ========================================================================== */
.pipeline-row { padding: 0.75rem 1rem; border-bottom: 1px solid var(--border-color); display: flex; justify-content: space-between; align-items: center; cursor: pointer; transition: background 0.2s; }
.pipeline-row:hover { background: var(--hover-color); }
.pipeline-row:last-child { border-bottom: none; }
.pipeline-info { display: flex; align-items: center; gap: 1rem; }
.pipeline-id { font-weight: 600; color: var(--accent-color); }
.pipeline-branch { color: var(--text-muted); }
.pipeline-time { color: var(--text-muted); font-size: 0.875rem; }

/* ==========================================================================
   Empty State & Loading
   ========================================================================== */
.empty-state { text-align: center; padding: 3rem; color: var(--text-muted); }
.empty-state-icon { font-size: 3rem; margin-bottom: 1rem; }
.loading { display: flex; justify-content: center; padding: 2rem; }
.spinner { width: 40px; height: 40px; border: 4px solid var(--border-color); border-top-color: var(--accent-color); border-radius: 50%; animation: spin 1s linear infinite; }

/* ==========================================================================
   Jobs Grid
   ========================================================================== */
.jobs-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 0.5rem; }
.job-card { background: var(--bg-color); border: 1px solid var(--border-color); border-radius: 6px; padding: 0.75rem; cursor: pointer; transition: all 0.2s; }
.job-card:hover { border-color: var(--accent-color); transform: translateY(-2px); }
.job-name { font-weight: 500; margin-bottom: 0.25rem; }
.job-stage { font-size: 0.75rem; color: var(--text-muted); }

/* ==========================================================================
   DAG Visualization
   ========================================================================== */
.dag-container { overflow-x: auto; padding: 1rem 0; position: relative; }
.dag-lines { position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; z-index: 1; }
.dag-line { stroke: var(--border-color); stroke-width: 2; fill: none; opacity: 0.6; marker-end: url(#arrowhead); }
.dag-line-same-stage { stroke: var(--accent-color); opacity: 0.8; }
.dag-stages { display: flex; gap: 0; min-width: max-content; align-items: flex-start; position: relative; z-index: 2; }
.dag-stage { min-width: 48px; display: flex; flex-direction: column; align-items: center; }
.dag-stage-header { font-size: 0.65rem; color: var(--text-muted); text-transform: uppercase; margin-bottom: 0.5rem; padding: 0.2rem 0.5rem; background: var(--hover-color); border-radius: 10px; text-align: center; white-space: nowrap; display: flex; align-items: center; gap: 0.25rem; cursor: pointer; transition: all 0.2s; }
.dag-stage-header:hover { background: var(--border-color); }
.run-stage-btn { background: none; border: none; color: var(--text-muted); cursor: pointer; font-size: 0.7rem; padding: 0; opacity: 0; transition: opacity 0.2s; }
.dag-stage-header:hover .run-stage-btn { opacity: 1; }
.run-stage-btn:hover { color: var(--accent-color); }
.dag-jobs { display: flex; flex-direction: column; gap: 0.5rem; align-items: center; }

/* DAG Job Circles */
.dag-job { width: 32px; height: 32px; border-radius: 50%; cursor: pointer; transition: all 0.2s; position: relative; display: flex; align-items: center; justify-content: center; border: none; background: var(--border-color); color: white; }
.dag-job:hover { transform: scale(1.1); box-shadow: 0 0 12px rgba(233, 69, 96, 0.5); }
.dag-job.selected { box-shadow: 0 0 0 3px var(--accent-color); }
.dag-job.status-success { background: var(--success-color); }
.dag-job.status-failed { background: var(--error-color); }
.dag-job.status-warning { background: var(--warning-color); color: black; }
.dag-job.status-running { background: var(--accent-color); animation: pulse-ring 1.5s infinite; }
.dag-job.status-pending { background: var(--text-muted); }
.dag-job-icon { font-size: 0.85rem; color: inherit; }

/* Manual jobs */
.dag-job.manual { border: 2px solid #f59e0b; box-shadow: 0 0 0 2px rgba(245, 158, 11, 0.2); }
.dag-job.manual.status-pending { cursor: pointer; }
.dag-job.manual.status-pending:hover { border-color: #d97706; box-shadow: 0 0 0 3px rgba(245, 158, 11, 0.4); }
.dag-job.manual::before { content: '\\23F8'; position: absolute; top: 1px; right: 1px; font-size: 8px; color: #f59e0b; opacity: 0.8; }
.dag-job.manual:hover::before { opacity: 1; }

/* DAG Tooltips */
.dag-job-tooltip { position: absolute; bottom: 100%; left: 50%; transform: translateX(-50%); background: var(--surface-color); border: 1px solid var(--border-color); padding: 0.5rem 0.75rem; border-radius: 6px; white-space: nowrap; font-size: 0.75rem; opacity: 0; visibility: hidden; transition: all 0.2s; z-index: 1000; pointer-events: none; margin-bottom: 8px; color: var(--text-color); }
.dag-job-tooltip::after { content: ''; position: absolute; top: 100%; left: 50%; transform: translateX(-50%); border: 6px solid transparent; border-top-color: var(--border-color); }
.dag-job:hover .dag-job-tooltip { opacity: 1; visibility: visible; }
.dag-job-tooltip-name { font-weight: 600; margin-bottom: 0.25rem; color: var(--text-color); }
.dag-job-tooltip-info { color: var(--text-muted); }

/* DAG Legend */
.dag-legend { display: flex; gap: 1rem; margin-bottom: 1rem; flex-wrap: wrap; position: relative; z-index: 1; }
.dag-legend-item { display: flex; align-items: center; gap: 0.25rem; font-size: 0.75rem; color: var(--text-muted); }
.dag-legend-color { width: 16px; height: 16px; border-radius: 50%; border: 2px solid; }

/* ==========================================================================
   Split View (Pipeline Detail)
   ========================================================================== */
.split-view { display: flex; gap: 0; height: calc(100vh - 200px); min-height: 400px; width: 100%; overflow: hidden; }
.split-left { flex: 0 0 450px; overflow: auto; min-width: 200px; max-width: 80%; padding-right: 0.5rem; }
.split-left.full-width { flex: 1; max-width: none; }
.split-divider { flex: 0 0 6px; background: var(--border-color); cursor: col-resize; position: relative; transition: background 0.2s; }
.split-divider:hover, .split-divider.dragging { background: var(--accent-color); }
.split-divider::before { content: ''; position: absolute; left: -4px; right: -4px; top: 0; bottom: 0; }
.split-right { flex: 1; display: flex; flex-direction: column; background: var(--surface-color); border-radius: 0; border: 1px solid var(--border-color); border-left: none; overflow: hidden; min-height: 0; min-width: 200px; }
.split-right-header { padding: 0.75rem 1rem; border-bottom: 1px solid var(--border-color); display: flex; justify-content: space-between; align-items: center; background: var(--hover-color); }
.split-right-header h3 { font-size: 0.9rem; font-weight: 600; }
.split-right-body { flex: 1; overflow: hidden; display: flex; flex-direction: column; min-height: 0; }

/* ==========================================================================
   Log Viewer
   ========================================================================== */
.live-log-viewer { flex: 1; background: var(--log-bg); color: var(--log-text); font-family: 'Monaco', 'Menlo', 'Consolas', monospace; font-size: 0.75rem; overflow: auto; padding: 0.5rem; min-height: 0; }
.live-log-line { display: flex; line-height: 1.4; }
.live-log-line-number { color: var(--log-line-number); min-width: 40px; text-align: right; padding-right: 0.75rem; user-select: none; }
.live-log-content { white-space: pre-wrap; word-break: break-all; }
.log-status-bar { padding: 0.5rem 1rem; border-top: 1px solid var(--border-color); font-size: 0.75rem; color: var(--text-muted); display: flex; justify-content: space-between; align-items: center; background: var(--hover-color); }
.auto-scroll-indicator { display: flex; align-items: center; gap: 0.5rem; }
.auto-scroll-indicator.active { color: var(--success-color); }

.log-viewer, .yaml-viewer { background: var(--log-bg); color: var(--log-text); font-family: 'Monaco', 'Menlo', 'Consolas', monospace; font-size: 0.8rem; padding: 1rem; max-height: 600px; overflow: auto; border-radius: 4px; white-space: pre; tab-size: 2; }
.log-line { display: flex; }
.log-line-number { color: var(--log-line-number); width: 50px; text-align: right; padding-right: 1rem; user-select: none; }

/* ==========================================================================
   ANSI Color Classes
   ========================================================================== */
.ansi-black { color: #586e75; }
.ansi-red { color: #dc322f; }
.ansi-green { color: #859900; }
.ansi-yellow { color: #b58900; }
.ansi-blue { color: #268bd2; }
.ansi-magenta { color: #d33682; }
.ansi-cyan { color: #2aa198; }
.ansi-white { color: #eee8d5; }
.ansi-bright-black { color: #657b83; }
.ansi-bright-red { color: #cb4b16; }
.ansi-bright-green { color: #98c379; }
.ansi-bright-yellow { color: #e5c07b; }
.ansi-bright-blue { color: #83a598; }
.ansi-bright-magenta { color: #c678dd; }
.ansi-bright-cyan { color: #56b6c2; }
.ansi-bright-white { color: #fdf6e3; }
.ansi-bg-black { background: #002b36; }
.ansi-bg-red { background: #dc322f; }
.ansi-bg-green { background: #859900; }
.ansi-bg-yellow { background: #b58900; }
.ansi-bg-blue { background: #268bd2; }
.ansi-bg-magenta { background: #d33682; }
.ansi-bg-cyan { background: #2aa198; }
.ansi-bg-white { background: #eee8d5; }
.ansi-bold { font-weight: bold; }
.ansi-dim { opacity: 0.7; }
.ansi-italic { font-style: italic; }
.ansi-underline { text-decoration: underline; }

/* ==========================================================================
   Artifacts
   ========================================================================== */
.artifacts-container { margin-top: 1rem; }
.artifact-list { display: flex; flex-direction: column; gap: 0.25rem; }
.artifact-item { display: flex; align-items: center; justify-content: space-between; padding: 0.5rem 0.75rem; background: var(--bg-color); border: 1px solid var(--border-color); border-radius: 4px; transition: all 0.2s; }
.artifact-item:hover { border-color: var(--accent-color); }
.artifact-info { display: flex; align-items: center; gap: 0.5rem; }
.artifact-icon { color: var(--text-muted); }
.artifact-name { font-family: monospace; font-size: 0.85rem; }
.artifact-size { font-size: 0.75rem; color: var(--text-muted); }
.artifact-download { color: var(--accent-color); text-decoration: none; font-size: 0.75rem; padding: 0.25rem 0.5rem; border: 1px solid var(--accent-color); border-radius: 4px; transition: all 0.2s; }
.artifact-download:hover { background: var(--accent-color); color: white; }

/* ==========================================================================
   Tabs
   ========================================================================== */
.tabs { display: flex; gap: 0; margin-bottom: 1rem; border-bottom: 1px solid var(--border-color); }
.tab { padding: 0.5rem 1rem; cursor: pointer; border-bottom: 2px solid transparent; transition: all 0.2s; color: var(--text-muted); }
.tab:hover { color: var(--text-color); }
.tab.active { color: var(--accent-color); border-bottom-color: var(--accent-color); }
.tab-content { display: none; }
.tab-content.active { display: block; }

/* ==========================================================================
   YAML Viewer
   ========================================================================== */
.yaml-line { display: flex; }
.yaml-line-number { color: #484f58; min-width: 40px; text-align: right; padding-right: 1rem; user-select: none; }
.yaml-content { flex: 1; }
.yaml-key { color: #7ee787; }
.yaml-string { color: #a5d6ff; }
.yaml-number { color: #79c0ff; }
.yaml-boolean { color: #ff7b72; }
.yaml-null { color: #ff7b72; font-style: italic; }
.yaml-anchor { color: #d2a8ff; }
.yaml-alias { color: #d2a8ff; }
.yaml-tag { color: #ffa657; }
.yaml-comment { color: #8b949e; font-style: italic; }
.yaml-variable { color: #ffa657; }
.yaml-keyword { color: #ff7b72; font-weight: 500; }
.yaml-list-marker { color: #79c0ff; }

/* ==========================================================================
   Buttons
   ========================================================================== */
.btn { display: inline-flex; align-items: center; gap: 0.5rem; padding: 0.5rem 1rem; border-radius: 6px; font-size: 0.875rem; font-weight: 500; cursor: pointer; border: none; transition: all 0.2s; }
.btn:disabled { opacity: 0.5; cursor: not-allowed; }
.btn-primary { background: var(--success-color); color: white; }
.btn-primary:hover:not(:disabled) { background: #d13550; }
.btn-secondary { background: var(--border-color); color: var(--text-color); }
.btn-secondary:hover:not(:disabled) { background: var(--hover-color); }
.btn-success { background: var(--success-color); color: white; }
.btn-success:hover:not(:disabled) { background: #43a047; }
.btn-danger { background: var(--error-color); color: white; }
.btn-danger:hover:not(:disabled) { background: #e53935; }
.btn-sm { padding: 0.25rem 0.5rem; font-size: 0.75rem; }

/* Button Groups */
.btn-group { display: inline-flex; border-radius: 6px; overflow: hidden; border: 1px solid var(--border-color); }
.btn-group .btn { border-radius: 0; border: none; padding: 0.375rem 0.75rem; }
.btn-group .btn:not(:last-child) { border-right: 1px solid var(--border-color); }
.btn-group .btn.active { background: var(--accent-color); color: white; }
.btn-group .btn:not(.active) { background: var(--surface-color); color: var(--text-muted); }
.btn-group .btn:not(.active):hover { background: var(--hover-color); color: var(--text-color); }

/* Special Buttons */
.close-btn { background: none; border: none; color: var(--text-muted); cursor: pointer; padding: 0.25rem; font-size: 1.2rem; line-height: 1; }
.close-btn:hover { color: var(--text-color); }
.header-actions { display: flex; gap: 0.5rem; align-items: center; }
.run-job-btn { background: var(--accent-color); border: none; color: black; cursor: pointer; padding: 0.25rem 0.75rem; font-size: 0.75rem; border-radius: 4px; font-weight: 500; transition: all 0.2s; }
.run-job-btn:hover { opacity: 0.9; transform: scale(1.02); }
.run-job-btn:disabled { background: var(--text-muted); cursor: not-allowed; opacity: 0.6; }

/* ==========================================================================
   Utilities
   ========================================================================== */
.back-link { color: var(--accent-color); text-decoration: none; display: inline-flex; align-items: center; gap: 0.5rem; margin-bottom: 1rem; }
.back-link:hover { text-decoration: underline; }
h2 { margin-bottom: 1rem; }
.flex-between { display: flex; justify-content: space-between; align-items: center; }
.mb-2 { margin-bottom: 0.5rem; }
.text-muted { color: var(--text-muted); }
.cwd-info { font-size: 0.75rem; color: var(--text-muted); margin-top: 0.25rem; }
.action-bar { display: flex; gap: 0.5rem; align-items: center; }

/* ==========================================================================
   Status Indicators
   ========================================================================== */
.status-indicator { display: flex; align-items: center; gap: 0.5rem; font-size: 0.875rem; }
.status-dot { width: 8px; height: 8px; border-radius: 50%; }
.status-dot.running { background: var(--accent-color); animation: pulse 1.5s infinite; }
.status-dot.idle { background: var(--success-color); }

/* ==========================================================================
   Init Progress
   ========================================================================== */
.init-progress { margin-top: 0.75rem; padding: 0.75rem; background: var(--bg-color); border-radius: 6px; border: 1px solid var(--border-color); }
.init-progress-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }
.init-progress-label { font-size: 0.875rem; color: var(--text-color); display: flex; align-items: center; gap: 0.5rem; }
.init-progress-phase { font-size: 0.75rem; color: var(--text-muted); }
.init-progress-bar { height: 4px; background: var(--border-color); border-radius: 2px; overflow: hidden; }
.init-progress-fill { height: 100%; background: var(--accent-color); border-radius: 2px; transition: width 0.3s ease; }
.init-spinner { display: inline-block; width: 12px; height: 12px; border: 2px solid var(--border-color); border-top-color: var(--accent-color); border-radius: 50%; animation: spin 1s linear infinite; }

/* ==========================================================================
   Resource Chart
   ========================================================================== */
.resource-chart-card { margin-bottom: 1rem; }
.resource-chart-container { position: relative; height: 150px; }
.resource-toggle-btn { font-size: 0.7rem; padding: 0.2rem 0.5rem; }
.resource-toggle-btn.active { background: var(--success-color); }
.resource-disabled-msg { text-align: center; padding: 1rem; color: var(--text-muted); font-size: 0.85rem; }

/* ==========================================================================
   Custom Scrollbars
   ========================================================================== */
::-webkit-scrollbar { width: 8px; height: 8px; }
::-webkit-scrollbar-track { background: var(--bg-color); }
::-webkit-scrollbar-thumb { background: var(--border-color); border-radius: 4px; }
::-webkit-scrollbar-thumb:hover { background: var(--text-muted); }
* { scrollbar-width: thin; scrollbar-color: var(--border-color) var(--bg-color); }

    </style>
</head>
<body>
    <header class="app-header">
        <div class="container">
            <div class="header-content">
                <h1 class="app-title">
                    <a href="#/" class="logo">GitLab CI Local</a>
                </h1>
                <nav class="app-nav">
                    <a href="#/" class="nav-link" id="nav-pipelines">Pipelines</a>
                    <a href="#/yaml" class="nav-link" id="nav-yaml">YAML</a>
                    <div class="status-indicator" id="nav-status">
                        <div class="status-dot idle"></div>
                        <span>Ready</span>
                    </div>
                    <button class="nav-link" id="theme-toggle" onclick="toggleTheme()" title="Toggle theme" style="border:none;cursor:pointer;background:none;">
                        <span id="theme-icon">&#9789;</span>
                    </button>
                </nav>
            </div>
        </div>
    </header>
    <main class="app-main">
        <div class="container">
            <div id="app-root">
                <div class="loading"><div class="spinner"></div></div>
            </div>
        </div>
    </main>
    <script>${CHARTJS_LIB}</script>
    <script>
"use strict";
(() => {
  var __defProp = Object.defineProperty;
  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
  var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

  // src/web/frontend/utils/api-client.ts
  var APIClient = class {
    constructor(baseURL = "/api") {
      __publicField(this, "baseURL");
      this.baseURL = baseURL;
    }
    // Generic fetch wrapper with error handling
    async fetch(endpoint, options) {
      const response = await fetch(\`\${this.baseURL}\${endpoint}\`, options);
      if (!response.ok) {
        const error = await response.json().catch(() => ({ error: "Unknown error" }));
        throw new Error(error.error || \`HTTP \${response.status}\`);
      }
      return response.json();
    }
    // Pipeline endpoints
    async listPipelines(limit = 20, offset = 0) {
      return this.fetch(\`/pipelines?limit=\${limit}&offset=\${offset}\`);
    }
    async getPipeline(id) {
      return this.fetch(\`/pipelines/\${id}\`);
    }
    async listJobs(pipelineId) {
      return this.fetch(\`/pipelines/\${pipelineId}/jobs\`);
    }
    async getExpandedYaml(pipelineId) {
      return this.fetch(\`/pipelines/\${pipelineId}/yaml\`);
    }
    async cancelPipeline() {
      return this.fetch("/pipelines/cancel", { method: "POST" });
    }
    // Job endpoints
    async getJob(id) {
      return this.fetch(\`/jobs/\${id}\`);
    }
    async getJobLogs(id, offset = 0, limit = 1e3) {
      return this.fetch(\`/jobs/\${id}/logs?offset=\${offset}&limit=\${limit}\`);
    }
    // Artifact endpoints
    async listArtifacts(jobId) {
      return this.fetch(\`/jobs/\${jobId}/artifacts\`);
    }
    getArtifactDownloadURL(jobId, path) {
      return \`\${this.baseURL}/jobs/\${jobId}/artifacts/\${path}\`;
    }
    // Stats endpoint
    async getStats() {
      return this.fetch("/stats");
    }
    // Resource monitor endpoints
    async getResourceMonitorStatus() {
      return this.fetch("/resource-monitor/status");
    }
    async enableResourceMonitor() {
      return this.fetch("/resource-monitor/enable", { method: "POST" });
    }
    async disableResourceMonitor() {
      return this.fetch("/resource-monitor/disable", { method: "POST" });
    }
    // Config endpoints
    async getSourceYaml() {
      return this.fetch("/config/yaml");
    }
    async getExpandedYamlConfig() {
      return this.fetch("/config/expanded-yaml");
    }
    async getConfig() {
      return this.fetch("/config");
    }
    // Pipeline control endpoints
    async getPipelineStatus() {
      return this.fetch("/pipelines/status");
    }
    async getPipelineStructure() {
      return this.fetch("/pipeline-structure");
    }
    async runPipeline(jobs, manualJobs) {
      const body = {};
      if (jobs && jobs.length > 0) {
        body.jobs = jobs;
      }
      if (manualJobs && manualJobs.length > 0) {
        body.manualJobs = manualJobs;
      }
      return this.fetch("/pipelines/run", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      });
    }
    async runJob(jobId) {
      return this.fetch(\`/jobs/\${jobId}/run\`, { method: "POST" });
    }
    async runStage(stageName) {
      return this.fetch(\`/stages/\${encodeURIComponent(stageName)}/run\`, { method: "POST" });
    }
  };
  var apiClient = new APIClient();

  // src/web/frontend/utils/format-utils.ts
  var JOB_COLORS = [
    { cpu: "#4CAF50", memory: "#81C784" },
    // Green
    { cpu: "#2196F3", memory: "#64B5F6" },
    // Blue
    { cpu: "#FF9800", memory: "#FFB74D" },
    // Orange
    { cpu: "#9C27B0", memory: "#BA68C8" },
    // Purple
    { cpu: "#F44336", memory: "#E57373" },
    // Red
    { cpu: "#00BCD4", memory: "#4DD0E1" },
    // Cyan
    { cpu: "#795548", memory: "#A1887F" },
    // Brown
    { cpu: "#607D8B", memory: "#90A4AE" }
    // Blue Grey
  ];
  function formatDate(timestamp) {
    if (!timestamp) return "N/A";
    const date = new Date(timestamp);
    return date.toLocaleString();
  }
  function formatDuration(duration) {
    if (!duration) return "N/A";
    const seconds = Math.floor(duration / 1e3);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    if (hours > 0) {
      return \`\${hours}h \${minutes % 60}m\`;
    } else if (minutes > 0) {
      return \`\${minutes}m \${seconds % 60}s\`;
    } else {
      return \`\${seconds}s\`;
    }
  }
  function formatBytes(bytes) {
    if (!bytes || bytes === 0) return "0 B";
    const units = ["B", "KB", "MB", "GB", "TB"];
    const i = Math.floor(Math.log(bytes) / Math.log(1024));
    return (bytes / Math.pow(1024, i)).toFixed(1) + " " + units[i];
  }
  function getStatusBadgeClass(status) {
    const map = {
      success: "badge-success",
      failed: "badge-error",
      running: "badge-running",
      pending: "badge-pending",
      canceled: "badge-warning",
      skipped: "badge-warning"
    };
    return "badge " + (map[status] || "badge-pending");
  }
  function getStatusIcon(status) {
    const icons = {
      success: "\\u2713",
      // ✓
      failed: "\\u2715",
      // ✕
      warning: "!",
      running: "\\u25C9",
      // ◉
      pending: "\\u25CB"
      // ○
    };
    return icons[status] || "\\u25CB";
  }
  function escapeHtml(text) {
    const div = document.createElement("div");
    div.textContent = text;
    return div.innerHTML;
  }

  // src/web/frontend/utils/ansi-parser.ts
  var ANSI_COLOR_MAP = {
    "30": "ansi-black",
    "31": "ansi-red",
    "32": "ansi-green",
    "33": "ansi-yellow",
    "34": "ansi-blue",
    "35": "ansi-magenta",
    "36": "ansi-cyan",
    "37": "ansi-white",
    "90": "ansi-bright-black",
    "91": "ansi-bright-red",
    "92": "ansi-bright-green",
    "93": "ansi-bright-yellow",
    "94": "ansi-bright-blue",
    "95": "ansi-bright-magenta",
    "96": "ansi-bright-cyan",
    "97": "ansi-bright-white",
    "40": "ansi-bg-black",
    "41": "ansi-bg-red",
    "42": "ansi-bg-green",
    "43": "ansi-bg-yellow",
    "44": "ansi-bg-blue",
    "45": "ansi-bg-magenta",
    "46": "ansi-bg-cyan",
    "47": "ansi-bg-white",
    "1": "ansi-bold",
    "2": "ansi-dim",
    "3": "ansi-italic",
    "4": "ansi-underline"
  };
  function escapeHtml2(text) {
    const div = document.createElement("div");
    div.textContent = text;
    return div.innerHTML;
  }
  function parseAnsiColors(text) {
    let result = "";
    let activeClasses = [];
    const escaped = escapeHtml2(text.replace(/\\x1b\\[|\\u001b\\[/g, "\\x1B["));
    const parts = escaped.split(/(\\x1b\\[[0-9;]*m)/g);
    for (const part of parts) {
      const match = part.match(/^\\x1b\\[([0-9;]*)m$/);
      if (match) {
        const codes = match[1].split(";");
        for (const code of codes) {
          if (code === "0" || code === "") {
            activeClasses = [];
          } else if (ANSI_COLOR_MAP[code]) {
            activeClasses.push(ANSI_COLOR_MAP[code]);
          }
        }
      } else if (part) {
        if (activeClasses.length > 0) {
          result += \`<span class="\${activeClasses.join(" ")}">\${part}</span>\`;
        } else {
          result += part;
        }
      }
    }
    return result || escapeHtml2(text);
  }

  // src/web/frontend/utils/yaml-highlighter.ts
  var GITLAB_KEYWORDS = [
    "stages",
    "variables",
    "before_script",
    "after_script",
    "script",
    "image",
    "services",
    "cache",
    "artifacts",
    "dependencies",
    "needs",
    "rules",
    "only",
    "except",
    "when",
    "allow_failure",
    "retry",
    "timeout",
    "include",
    "extends",
    "trigger",
    "parallel",
    "resource_group",
    "environment",
    "coverage",
    "interruptible",
    "tags",
    "stage",
    "default",
    "workflow",
    "pages",
    "release",
    "secrets",
    "id_tokens"
  ];
  function highlightValue(text) {
    if (!text) return "";
    if (/^(true|false)$/.test(text.trim())) {
      return \`<span class="yaml-boolean">\${text}</span>\`;
    }
    if (/^(null|~)$/.test(text.trim())) {
      return \`<span class="yaml-null">\${text}</span>\`;
    }
    if (/^-?\\d+\\.?\\d*$/.test(text.trim())) {
      return \`<span class="yaml-number">\${text}</span>\`;
    }
    const tokens = [];
    let remaining = text;
    while (remaining.length > 0) {
      let match;
      if (match = remaining.match(/^("[^"]*")/)) {
        tokens.push(\`<span class="yaml-string">\${match[1]}</span>\`);
        remaining = remaining.slice(match[1].length);
      } else if (match = remaining.match(/^('[^']*')/)) {
        tokens.push(\`<span class="yaml-string">\${match[1]}</span>\`);
        remaining = remaining.slice(match[1].length);
      } else if (match = remaining.match(/^(&amp;[a-zA-Z_][a-zA-Z0-9_-]*)/)) {
        tokens.push(\`<span class="yaml-anchor">\${match[1]}</span>\`);
        remaining = remaining.slice(match[1].length);
      } else if (match = remaining.match(/^(\\*[a-zA-Z_][a-zA-Z0-9_-]*)/)) {
        tokens.push(\`<span class="yaml-alias">\${match[1]}</span>\`);
        remaining = remaining.slice(match[1].length);
      } else if (match = remaining.match(/^(\\$\\{[A-Za-z_][A-Za-z0-9_]*\\})/)) {
        tokens.push(\`<span class="yaml-variable">\${match[1]}</span>\`);
        remaining = remaining.slice(match[1].length);
      } else if (match = remaining.match(/^(\\$[A-Za-z_][A-Za-z0-9_]*)/)) {
        tokens.push(\`<span class="yaml-variable">\${match[1]}</span>\`);
        remaining = remaining.slice(match[1].length);
      } else if (match = remaining.match(/^(\\s)(#.*)$/)) {
        tokens.push(match[1] + \`<span class="yaml-comment">\${match[2]}</span>\`);
        remaining = "";
      } else {
        tokens.push(remaining[0]);
        remaining = remaining.slice(1);
      }
    }
    return tokens.join("");
  }
  function highlightYaml(content) {
    const lines = content.split("\\n");
    return lines.map((line, i) => {
      const escaped = escapeHtml(line);
      let result = "";
      if (/^\\s*#/.test(line)) {
        result = \`<span class="yaml-comment">\${escaped}</span>\`;
      } else {
        const listMatch = escaped.match(/^(\\s*)(-)(\\s)(.*)$/);
        const keyMatch = escaped.match(/^(\\s*)([\\w.-]+):(\\s*)(.*)$/);
        if (listMatch) {
          const indent = listMatch[1];
          const value = listMatch[4];
          result = indent + '<span class="yaml-list-marker">-</span> ' + highlightValue(value);
        } else if (keyMatch) {
          const kindent = keyMatch[1];
          const key = keyMatch[2];
          const spacing = keyMatch[3];
          const val = keyMatch[4];
          const keyClass = GITLAB_KEYWORDS.includes(key) ? "yaml-keyword" : "yaml-key";
          result = kindent + \`<span class="\${keyClass}">\${key}</span>:\` + spacing + highlightValue(val);
        } else {
          result = highlightValue(escaped);
        }
      }
      return \`<div class="yaml-line"><span class="yaml-line-number">\${i + 1}</span><span class="yaml-content">\${result}</span></div>\`;
    }).join("");
  }

  // src/web/frontend/app-bundle.ts
  var pipelineRunning = false;
  var queuedJobs = [];
  var resourceChart = null;
  var resourceMonitorEnabled = localStorage.getItem("gcl-resource-monitor") !== "false";
  var statsHistory = {};
  var jobColorIndex = 0;
  var jobColorMap = {};
  var selectedJobId = null;
  var logAutoScroll = true;
  var renderedLogCount = 0;
  var logRefreshInterval = null;
  var selectJobCounter = 0;
  var yamlViewMode = "source";
  var cachedSourceYaml = null;
  var cachedExpandedYaml = null;
  var refreshInterval = null;
  var routerCounter = 0;
  function getStoredTheme() {
    return localStorage.getItem("gcl-theme") || "system";
  }
  function applyTheme(theme) {
    const root = document.documentElement;
    root.classList.remove("light-theme", "dark-theme");
    if (theme === "light") {
      root.classList.add("light-theme");
    } else if (theme === "dark") {
      root.classList.add("dark-theme");
    }
    localStorage.setItem("gcl-theme", theme);
    updateThemeIcon(theme);
  }
  function updateThemeIcon(theme) {
    const icon = document.getElementById("theme-icon");
    if (!icon) return;
    if (theme === "light") {
      icon.innerHTML = "&#9788;";
      icon.title = "Light mode (click for dark)";
    } else if (theme === "dark") {
      icon.innerHTML = "&#9789;";
      icon.title = "Dark mode (click for system)";
    } else {
      icon.innerHTML = "&#9680;";
      icon.title = "System theme (click for light)";
    }
  }
  function toggleTheme() {
    const current = getStoredTheme();
    let next;
    if (current === "system") {
      next = "light";
    } else if (current === "light") {
      next = "dark";
    } else {
      next = "system";
    }
    applyTheme(next);
  }
  applyTheme(getStoredTheme());
  async function fetchPipelines() {
    const res = await apiClient.listPipelines();
    return res.pipelines || [];
  }
  async function fetchPipeline(id) {
    return apiClient.getPipeline(id);
  }
  async function fetchJobLogs(jobId, limit = 1e5) {
    return apiClient.getJobLogs(jobId, 0, limit);
  }
  async function fetchJobArtifacts(jobId) {
    return apiClient.listArtifacts(jobId);
  }
  async function fetchJob(jobId) {
    return apiClient.getJob(jobId);
  }
  async function fetchYaml() {
    return apiClient.getSourceYaml();
  }
  async function fetchExpandedYaml() {
    return apiClient.getExpandedYamlConfig();
  }
  async function fetchConfig() {
    return apiClient.getConfig();
  }
  async function fetchPipelineStatus() {
    return apiClient.getPipelineStatus();
  }
  async function fetchPipelineStructure() {
    return apiClient.getPipelineStructure();
  }
  async function runPipeline(jobs, manualJobs) {
    return apiClient.runPipeline(jobs, manualJobs);
  }
  async function runSingleJob(jobId) {
    return apiClient.runJob(jobId);
  }
  async function cancelPipeline() {
    return apiClient.cancelPipeline();
  }
  function getJobColor(jobName) {
    if (!jobColorMap[jobName]) {
      jobColorMap[jobName] = JOB_COLORS[jobColorIndex % JOB_COLORS.length];
      jobColorIndex++;
    }
    return jobColorMap[jobName];
  }
  function updateNavbarStatus(isRunning) {
    const navStatus = document.getElementById("nav-status");
    if (navStatus) {
      if (isRunning) {
        navStatus.innerHTML = '<div class="status-dot running"></div><span>Running</span>';
      } else {
        navStatus.innerHTML = '<div class="status-dot idle"></div><span>Ready</span>';
      }
    }
  }
  function updateNav(hash) {
    document.querySelectorAll(".nav-link").forEach((el) => el.classList.remove("active"));
    if (hash === "/yaml") {
      document.getElementById("nav-yaml")?.classList.add("active");
    } else {
      document.getElementById("nav-pipelines")?.classList.add("active");
    }
  }
  var manualJobDialogResolve = null;
  function closeManualDialog() {
    document.querySelector(".modal-backdrop")?.remove();
    document.querySelector(".manual-job-dialog")?.remove();
    if (manualJobDialogResolve) {
      manualJobDialogResolve(null);
      manualJobDialogResolve = null;
    }
  }
  function confirmManualJobs() {
    const checkboxes = document.querySelectorAll('input[name="manual-job"]:checked');
    const selected = Array.from(checkboxes).map((cb) => cb.value);
    document.querySelector(".modal-backdrop")?.remove();
    document.querySelector(".manual-job-dialog")?.remove();
    if (manualJobDialogResolve) {
      manualJobDialogResolve(selected);
      manualJobDialogResolve = null;
    }
  }
  function selectAllManualJobs() {
    document.querySelectorAll('input[name="manual-job"]').forEach((cb) => cb.checked = true);
  }
  function selectNoManualJobs() {
    document.querySelectorAll('input[name="manual-job"]').forEach((cb) => cb.checked = false);
  }
  function toggleResourceMonitor() {
    resourceMonitorEnabled = !resourceMonitorEnabled;
    localStorage.setItem("gcl-resource-monitor", resourceMonitorEnabled ? "true" : "false");
    updateResourceChartVisibility();
  }
  function updateResourceChartVisibility() {
    const container = document.getElementById("resource-chart-container");
    const disabledMsg = document.getElementById("resource-disabled-msg");
    const toggleBtn = document.getElementById("resource-toggle-btn");
    if (container) container.style.display = resourceMonitorEnabled ? "block" : "none";
    if (disabledMsg) disabledMsg.style.display = resourceMonitorEnabled ? "none" : "block";
    if (toggleBtn) {
      toggleBtn.textContent = resourceMonitorEnabled ? "Disable" : "Enable";
      toggleBtn.className = "btn btn-sm resource-toggle-btn" + (resourceMonitorEnabled ? " active" : "");
    }
  }
  function initResourceChart() {
    const canvas = document.getElementById("resource-chart");
    if (!canvas || typeof Chart === "undefined") return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    resourceChart = new Chart(ctx, {
      type: "line",
      data: { labels: [], datasets: [] },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        animation: { duration: 0 },
        interaction: { mode: "index", intersect: false },
        plugins: {
          legend: { display: false },
          tooltip: {
            callbacks: {
              label: function(ctx2) {
                if (ctx2.dataset.yAxisID === "y-memory") {
                  return ctx2.dataset.label + ": " + (ctx2.parsed.y / 1024).toFixed(2) + " GB";
                }
                return ctx2.dataset.label + ": " + ctx2.parsed.y.toFixed(1) + "%";
              }
            }
          }
        },
        scales: {
          x: { display: true, ticks: { maxTicksLimit: 6, font: { size: 9 } } },
          "y-cpu": {
            type: "linear",
            display: true,
            position: "left",
            beginAtZero: true,
            title: { display: true, text: "CPU %", font: { size: 9 } },
            ticks: { font: { size: 9 }, callback: (v) => v + "%" }
          },
          "y-memory": {
            type: "linear",
            display: true,
            position: "right",
            beginAtZero: true,
            title: { display: true, text: "Memory (GB)", font: { size: 9 } },
            ticks: { font: { size: 9 }, callback: (v) => (v / 1024).toFixed(1) + " GB" },
            grid: { drawOnChartArea: false }
          }
        }
      }
    });
  }
  function updateResourceChart(containerStats) {
    if (!resourceMonitorEnabled || !resourceChart) return;
    const now = Date.now();
    const MB = 1024 * 1024;
    const cutoffTime = now - 12e4;
    if (containerStats && containerStats.length > 0) {
      containerStats.forEach((stat) => {
        if (!statsHistory[stat.jobName]) statsHistory[stat.jobName] = [];
        statsHistory[stat.jobName].push({
          timestamp: stat.timestamp || now,
          cpu: stat.cpuPercent,
          memoryMB: (stat.memoryBytes || 0) / MB
        });
      });
    }
    Object.keys(statsHistory).forEach((jobName) => {
      statsHistory[jobName] = statsHistory[jobName].filter((h) => h.timestamp >= cutoffTime);
      if (statsHistory[jobName].length === 0) {
        delete statsHistory[jobName];
      }
    });
    if (Object.keys(statsHistory).length === 0) {
      resourceChart.data.labels = [];
      resourceChart.data.datasets = [];
      resourceChart.update("none");
      return;
    }
    const allTimestamps = /* @__PURE__ */ new Set();
    Object.values(statsHistory).forEach((history) => {
      history.forEach((h) => allTimestamps.add(h.timestamp));
    });
    const sortedTs = Array.from(allTimestamps).sort((a, b) => a - b);
    const labels = sortedTs.map((ts) => {
      const d = new Date(ts);
      return d.toLocaleTimeString([], { minute: "2-digit", second: "2-digit" });
    });
    const datasets = [];
    Object.keys(statsHistory).forEach((jobName) => {
      const colors = getJobColor(jobName);
      const history = statsHistory[jobName];
      const historyMap = {};
      history.forEach((h) => {
        historyMap[h.timestamp] = h;
      });
      const cpuData = sortedTs.map((ts) => {
        const h = historyMap[ts];
        return h ? h.cpu : null;
      });
      const memData = sortedTs.map((ts) => {
        const h = historyMap[ts];
        return h ? h.memoryMB : null;
      });
      datasets.push({
        label: jobName + " CPU",
        data: cpuData,
        borderColor: colors.cpu,
        backgroundColor: colors.cpu,
        borderWidth: 2,
        fill: false,
        tension: 0.1,
        pointRadius: 2,
        yAxisID: "y-cpu"
      });
      datasets.push({
        label: jobName + " Mem",
        data: memData,
        borderColor: colors.memory,
        backgroundColor: colors.memory,
        borderWidth: 2,
        borderDash: [5, 5],
        fill: false,
        tension: 0.1,
        pointRadius: 2,
        yAxisID: "y-memory"
      });
    });
    resourceChart.data.labels = labels;
    resourceChart.data.datasets = datasets;
    resourceChart.update("none");
  }
  function renderResourceChart() {
    const displayStyle = resourceMonitorEnabled ? "block" : "none";
    const disabledStyle = resourceMonitorEnabled ? "none" : "block";
    const btnClass = "btn btn-sm resource-toggle-btn" + (resourceMonitorEnabled ? " active" : "");
    const btnText = resourceMonitorEnabled ? "Disable" : "Enable";
    return '<div class="card resource-chart-card"><div class="card-header"><h3 style="font-size:0.9rem;margin:0">Resource Usage</h3><button id="resource-toggle-btn" class="' + btnClass + '" onclick="toggleResourceMonitor()">' + btnText + '</button></div><div class="card-body" style="padding:0.5rem"><div id="resource-chart-container" class="resource-chart-container" style="display:' + displayStyle + '"><canvas id="resource-chart"></canvas></div><div id="resource-disabled-msg" class="resource-disabled-msg" style="display:' + disabledStyle + '">Resource monitoring disabled</div></div></div>';
  }
  function renderDagVisualization(jobs, selectedId, pipelineId, stageOrderOverride) {
    const stageMap = {};
    const stageOrder = stageOrderOverride || [];
    jobs.forEach((j) => {
      if (!stageMap[j.stage]) {
        stageMap[j.stage] = [];
        if (!stageOrderOverride) {
          stageOrder.push(j.stage);
        }
      }
      stageMap[j.stage].push(j);
    });
    const stagesHtml = stageOrder.filter((stage) => stageMap[stage] && stageMap[stage].length > 0).map((stage) => {
      const stageJobs = stageMap[stage];
      const jobsHtml = stageJobs.map((j) => {
        const needs = j.needs || [];
        const needsInfo = needs.length > 0 ? "Needs: " + needs.join(", ") : "";
        const selectedClass = selectedId === j.id ? " selected" : "";
        const manualClass = j.isManual ? " manual" : "";
        const icon = getStatusIcon(j.status);
        let clickHandler;
        if (j.isManual && j.status === "pending") {
          clickHandler = \`handleTriggerManualJob('\${j.id}', '\${escapeHtml(j.name).replace(/'/g, "\\\\'")}')\`;
        } else if (pipelineId) {
          clickHandler = \`location.hash='#/pipeline/\${pipelineId}'; setTimeout(function() { selectJob('\${j.id}'); }, 100);\`;
        } else {
          clickHandler = \`selectJob('\${j.id}')\`;
        }
        const manualTooltip = j.isManual && j.status === "pending" ? '<div class="dag-job-tooltip-info">\\u23F8 Manual job \\u2022 Click to trigger</div>' : j.isManual ? '<div class="dag-job-tooltip-info">\\u23F8 Manual job</div>' : "";
        return '<div class="dag-job status-' + j.status + selectedClass + manualClass + '" data-job-id="' + j.id + '" data-job-name="' + escapeHtml(j.name) + '" data-needs="' + escapeHtml(needs.join(",")) + '" onclick="' + clickHandler + '"><span class="dag-job-icon">' + icon + '</span><div class="dag-job-tooltip"><div class="dag-job-tooltip-name">' + escapeHtml(j.name) + "</div>" + manualTooltip + (j.description ? '<div class="dag-job-tooltip-info">' + escapeHtml(j.description) + "</div>" : "") + '<div class="dag-job-tooltip-info">' + j.status + (j.duration ? " \\u2022 " + formatDuration(j.duration) : "") + "</div>" + (needsInfo ? '<div class="dag-job-tooltip-info">' + needsInfo + "</div>" : "") + "</div></div>";
      }).join("");
      return '<div class="dag-stage"><div class="dag-stage-header"><span>' + escapeHtml(stage) + \`</span><button class="run-stage-btn" onclick="event.stopPropagation(); handleRunStage('\` + escapeHtml(stage) + \`')" title="Run stage">\\u25B6</button></div><div class="dag-jobs">\` + jobsHtml + "</div></div>";
    }).join("");
    const legend = '<div class="dag-legend"><div class="dag-legend-item"><div class="dag-legend-color" style="border:none;background:var(--text-muted)"></div>Pending</div><div class="dag-legend-item"><div class="dag-legend-color" style="border:none;background:var(--accent-color)"></div>Running</div><div class="dag-legend-item"><div class="dag-legend-color" style="border:none;background:var(--success-color)"></div>Success</div><div class="dag-legend-item"><div class="dag-legend-color" style="border:none;background:var(--error-color)"></div>Failed</div></div>';
    return legend + '<div class="dag-container"><svg class="dag-lines"></svg><div class="dag-stages">' + stagesHtml + "</div></div>";
  }
  function drawDependencyLines() {
    const svg = document.querySelector(".dag-lines");
    if (!svg) return;
    svg.innerHTML = "";
    const defs = document.createElementNS("http://www.w3.org/2000/svg", "defs");
    defs.innerHTML = '<marker id="arrowhead" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto"><polygon points="0 0, 10 3.5, 0 7" fill="var(--border-color)" opacity="0.6"/></marker><marker id="arrowhead-accent" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto"><polygon points="0 0, 10 3.5, 0 7" fill="var(--accent-color)" opacity="0.8"/></marker>';
    svg.appendChild(defs);
    const container = svg.closest(".dag-container");
    if (!container) return;
    const containerRect = container.getBoundingClientRect();
    const jobs = container.querySelectorAll(".dag-job");
    const jobsByName = {};
    jobs.forEach((job) => {
      const name = job.getAttribute("data-job-name");
      if (name) {
        jobsByName[name] = job;
      }
    });
    jobs.forEach((job) => {
      const needsAttr = job.getAttribute("data-needs");
      if (!needsAttr) return;
      const needs = needsAttr.split(",").filter((n) => n.trim());
      needs.forEach((needName) => {
        const sourceJob = jobsByName[needName.trim()];
        if (!sourceJob) return;
        const sourceRect = sourceJob.getBoundingClientRect();
        const targetRect = job.getBoundingClientRect();
        const sameStage = Math.abs(sourceRect.left - targetRect.left) < 50;
        const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
        if (sameStage) {
          let x1 = sourceRect.left + sourceRect.width / 2 - containerRect.left;
          let y1 = sourceRect.bottom - containerRect.top;
          let x2 = targetRect.left + targetRect.width / 2 - containerRect.left;
          let y2 = targetRect.top - containerRect.top;
          if (y2 < y1) {
            const temp = y1;
            y1 = y2;
            y2 = temp;
            const tempX = x1;
            x1 = x2;
            x2 = tempX;
            y1 = sourceRect.top - containerRect.top;
            y2 = targetRect.bottom - containerRect.top;
          }
          const midY = (y1 + y2) / 2;
          path.setAttribute("d", "M " + x1 + " " + y1 + " C " + x1 + " " + midY + ", " + x2 + " " + midY + ", " + x2 + " " + y2);
          path.setAttribute("class", "dag-line dag-line-same-stage");
          path.style.markerEnd = "url(#arrowhead-accent)";
        } else {
          const x1 = sourceRect.right - containerRect.left;
          const y1 = sourceRect.top + sourceRect.height / 2 - containerRect.top;
          const x2 = targetRect.left - containerRect.left;
          const y2 = targetRect.top + targetRect.height / 2 - containerRect.top;
          const midX = (x1 + x2) / 2;
          path.setAttribute("d", "M " + x1 + " " + y1 + " C " + midX + " " + y1 + ", " + midX + " " + y2 + ", " + x2 + " " + y2);
          path.setAttribute("class", "dag-line");
        }
        svg.appendChild(path);
      });
    });
  }
  function scheduleDependencyLinesDraw() {
    requestAnimationFrame(() => {
      setTimeout(drawDependencyLines, 50);
    });
  }
  function buildStructureJobs(structure, recentPipelineJobs) {
    const jobStatusMap = {};
    if (recentPipelineJobs && recentPipelineJobs.length > 0) {
      recentPipelineJobs.forEach((job) => {
        jobStatusMap[job.name] = {
          status: job.status,
          duration: job.duration,
          id: job.id
        };
      });
    }
    return (structure?.jobs || []).map((j) => {
      const recentJob = jobStatusMap[j.name];
      return {
        id: recentJob ? recentJob.id : j.id,
        name: j.name,
        stage: j.stage,
        status: recentJob ? recentJob.status : "pending",
        needs: j.needs || null,
        duration: recentJob ? recentJob.duration : null,
        isManual: j.isManual || false,
        description: j.description
      };
    });
  }
  function renderPipelinesSection(pipelines) {
    if (!pipelines.length) {
      return '<div class="card"><div class="card-header"><h2>Recent Pipelines</h2></div><div class="empty-state"><div class="empty-state-icon">&#128203;</div><div>No pipelines run yet</div><div class="text-muted">Click "Run Pipeline" above to start</div></div></div>';
    }
    const rows = pipelines.map(
      (p) => \`<div class="pipeline-row" onclick="showPipeline('\` + p.id + \`')"><div class="pipeline-info"><span class="pipeline-id">#\` + p.iid + '</span><span class="' + getStatusBadgeClass(p.status) + '">' + p.status + '</span><span class="pipeline-branch">' + (p.git_ref || "") + '</span></div><div class="pipeline-time">' + formatDate(p.created_at) + "</div></div>"
    ).join("");
    return '<div class="card"><div class="card-header"><h2>Recent Pipelines</h2></div><div class="card-body" style="padding:0">' + rows + "</div></div>";
  }
  function renderPipelineList(pipelines, status, structure, recentPipelineJobs) {
    const isRunning = status && status.running;
    pipelineRunning = isRunning;
    updateNavbarStatus(isRunning);
    const actionBtn = '<span id="action-btn">' + (isRunning ? '<button class="btn btn-danger" onclick="handleCancelPipeline()">Cancel Pipeline</button>' : '<button class="btn btn-primary" onclick="handleRunPipeline()">&#9654; Run Pipeline</button>') + "</span>";
    const recentPipelineId = pipelines.length > 0 ? pipelines[0].id : null;
    let dagSection = "";
    if (structure && structure.exists && structure.jobs && structure.jobs.length > 0) {
      const structureJobs = buildStructureJobs(structure, recentPipelineJobs);
      const dagHtml = renderDagVisualization(structureJobs, null, recentPipelineId, structure?.stages);
      dagSection = '<div class="card"><div class="card-header"><h2>Pipeline Structure</h2>' + actionBtn + '</div><div class="card-body"><div id="dag-content">' + dagHtml + "</div></div></div>";
    } else {
      dagSection = '<div class="card"><div class="card-header"><h2>Pipeline Structure</h2>' + actionBtn + '</div><div class="empty-state"><div class="empty-state-icon">\\u{1F4C4}</div><div>No .gitlab-ci.yml found</div><div class="text-muted">Create a .gitlab-ci.yml file to get started</div></div></div>';
    }
    const pipelinesSection = '<div id="pipelines-section">' + renderPipelinesSection(pipelines) + "</div>";
    return dagSection + pipelinesSection;
  }
  function updatePipelineListContent(pipelines, status, structure, recentPipelineJobs) {
    const isRunning = status && status.running;
    pipelineRunning = isRunning;
    updateNavbarStatus(isRunning);
    const actionBtnEl = document.getElementById("action-btn");
    if (actionBtnEl) {
      actionBtnEl.innerHTML = isRunning ? '<button class="btn btn-danger" onclick="handleCancelPipeline()">Cancel Pipeline</button>' : '<button class="btn btn-primary" onclick="handleRunPipeline()">&#9654; Run Pipeline</button>';
    }
    const dagContent = document.getElementById("dag-content");
    if (dagContent && structure && structure.exists && structure.jobs) {
      const recentPipelineId = pipelines.length > 0 ? pipelines[0].id : null;
      const structureJobs = buildStructureJobs(structure, recentPipelineJobs);
      const existingDagJobs = dagContent.querySelectorAll(".dag-job");
      if (existingDagJobs.length === structureJobs.length && existingDagJobs.length > 0) {
        structureJobs.forEach((job) => {
          const jobEl = dagContent.querySelector('.dag-job[data-job-name="' + escapeHtml(job.name) + '"]');
          if (jobEl) {
            const manualClass = job.isManual ? " manual" : "";
            jobEl.className = "dag-job status-" + job.status + manualClass;
            const iconEl = jobEl.querySelector(".dag-job-icon");
            if (iconEl) {
              iconEl.textContent = getStatusIcon(job.status);
            }
            const tooltipInfo = jobEl.querySelector(".dag-job-tooltip-info");
            if (tooltipInfo) {
              tooltipInfo.textContent = job.status + (job.duration ? " \\u2022 " + formatDuration(job.duration) : "");
            }
          }
        });
      } else {
        dagContent.innerHTML = renderDagVisualization(structureJobs, null, recentPipelineId, structure?.stages);
        scheduleDependencyLinesDraw();
      }
    }
    const pipelinesSection = document.getElementById("pipelines-section");
    if (pipelinesSection) {
      pipelinesSection.innerHTML = renderPipelinesSection(pipelines);
    }
  }
  function renderInitProgress(p) {
    if (!p.init_phase || p.status !== "queued") {
      return "";
    }
    const progress = p.init_progress || 0;
    const message = p.init_message || "Initializing...";
    return '<div class="init-progress" id="init-progress"><div class="init-progress-header"><span class="init-progress-label"><span class="init-spinner"></span> ' + escapeHtml(message) + '</span><span class="init-progress-phase">' + progress + '%</span></div><div class="init-progress-bar"><div class="init-progress-fill" style="width: ' + progress + '%"></div></div></div>';
  }
  function renderPipelineDetail(data, selectedJob, logData, structure) {
    const p = data.pipeline;
    const jobs = data.jobs || [];
    const dagHtml = renderDagVisualization(jobs, selectedJobId, null, structure?.stages);
    const initProgressHtml = renderInitProgress(p);
    const leftPanelClass = selectedJob ? "split-left" : "split-left full-width";
    const resourceChartHtml = renderResourceChart();
    const leftPanel = '<div class="' + leftPanelClass + '"><a href="#/" class="back-link">&larr; Back to pipelines</a><div class="card"><div class="card-header"><div><h2>Pipeline #' + p.iid + '</h2></div><div style="display:flex;gap:0.5rem;align-items:center"><span id="pipeline-status" class="' + getStatusBadgeClass(p.status) + '">' + p.status + "</span>" + (p.status === "running" ? '<button class="btn btn-danger btn-sm" onclick="handleCancelPipeline()">Cancel</button>' : "") + '</div></div><div class="card-body"><p>Started: ' + formatDate(p.started_at) + '</p><p id="pipeline-duration">Duration: ' + formatDuration(p.duration) + "</p>" + initProgressHtml + "</div></div>" + resourceChartHtml + '<div class="card"><div class="card-header"><h2>Pipeline Graph</h2><span class="text-muted">Click a job to view logs</span></div><div class="card-body"><div id="pipeline-dag">' + dagHtml + "</div></div></div></div>";
    if (selectedJob && logData) {
      const logs = logData.logs || [];
      const totalLogs = logData.total || logs.length;
      const reachedLimit = logs.length < totalLogs;
      const logCountText = logs.length + " lines" + (reachedLimit ? " (reached limit of " + logs.length + ", total: " + totalLogs + ")" : "");
      const logLines = logs.map((l, i) => {
        return '<div class="live-log-line"><span class="live-log-line-number">' + (i + 1) + '</span><span class="live-log-content">' + parseAnsiColors(l.content) + "</span></div>";
      }).join("");
      const autoScrollClass = logAutoScroll ? " active" : "";
      const runBtnText = selectedJob.status === "pending" || selectedJob.status === "running" ? "Run" : "Retry";
      const runBtnDisabled = pipelineRunning ? " disabled" : "";
      const rightPanel = '<div class="split-right"><div class="split-right-header"><h3 id="job-header">' + escapeHtml(selectedJob.name) + ' <span class="' + getStatusBadgeClass(selectedJob.status) + '">' + selectedJob.status + \`</span></h3><div class="header-actions"><button class="run-job-btn" id="run-job-btn" onclick="handleRunJob('\` + selectedJob.id + "', '" + escapeHtml(selectedJob.name) + \`')"\` + runBtnDisabled + ">" + runBtnText + \`</button><button class="run-job-btn" style="background:var(--border-color);color:white" onclick="window.open('/api/jobs/\` + selectedJob.id + \`/logs/raw', '_blank')">Raw</button><button class="close-btn" onclick="closeLogPanel()">\\xD7</button></div></div><div class="split-right-body"><div class="live-log-viewer" id="live-log-viewer" onscroll="handleLogScroll()">\` + (logLines || '<div class="text-muted" style="padding:1rem">No logs yet</div>') + '</div></div><div class="log-status-bar"><span id="log-count">' + logCountText + '</span><div class="auto-scroll-indicator' + autoScrollClass + '"><span>' + (logAutoScroll ? "\\u25CF Auto-scroll ON" : "\\u25CB Auto-scroll OFF") + "</span></div></div></div>";
      setTimeout(() => {
        const container = document.querySelector(".app-main .container");
        if (container) container.classList.add("full-width");
        initSplitDivider();
      }, 0);
      return '<div class="split-view">' + leftPanel + '<div class="split-divider" id="split-divider"></div>' + rightPanel + "</div>";
    }
    setTimeout(() => {
      const container = document.querySelector(".app-main .container");
      if (container) container.classList.remove("full-width");
    }, 0);
    return '<div class="split-view">' + leftPanel + "</div>";
  }
  function initSplitDivider() {
    const divider = document.getElementById("split-divider");
    const splitView = document.querySelector(".split-view");
    const leftPanel = document.querySelector(".split-left");
    if (!divider || !splitView || !leftPanel) return;
    let isDragging = false;
    let startX = 0;
    let startWidth = 0;
    divider.addEventListener("mousedown", (e) => {
      isDragging = true;
      startX = e.clientX;
      startWidth = leftPanel.offsetWidth;
      divider.classList.add("dragging");
      document.body.style.cursor = "col-resize";
      document.body.style.userSelect = "none";
      e.preventDefault();
    });
    document.addEventListener("mousemove", (e) => {
      if (!isDragging) return;
      const delta = e.clientX - startX;
      let newWidth = startWidth + delta;
      const minWidth = 200;
      const maxWidth = splitView.offsetWidth - 200 - 6;
      newWidth = Math.max(minWidth, Math.min(maxWidth, newWidth));
      leftPanel.style.flex = "0 0 " + newWidth + "px";
    });
    document.addEventListener("mouseup", () => {
      if (!isDragging) return;
      isDragging = false;
      divider.classList.remove("dragging");
      document.body.style.cursor = "";
      document.body.style.userSelect = "";
    });
  }
  function renderArtifacts(artifacts, jobId) {
    if (!artifacts || artifacts.length === 0) {
      return '<div class="text-muted">No artifacts</div>';
    }
    const items = artifacts.map((a) => {
      return '<div class="artifact-item"><div class="artifact-info"><span class="artifact-icon">&#128196;</span><span class="artifact-name">' + escapeHtml(a.file_path) + '</span></div><div><span class="artifact-size">' + formatBytes(a.size) + '</span> <a href="/api/jobs/' + jobId + "/artifacts/" + encodeURIComponent(a.file_path) + '" class="artifact-download" download>Download</a></div></div>';
    }).join("");
    return '<div class="artifact-list">' + items + "</div>";
  }
  function renderJobLogs(data, jobId, runStatus) {
    const logs = data.logs || [];
    const artifacts = data.artifacts || [];
    const job = data.job || {};
    const isRunning = runStatus && runStatus.running;
    const lines = logs.map((l, i) => {
      return '<div class="log-line"><span class="log-line-number">' + (i + 1) + "</span><span>" + escapeHtml(l.content) + "</span></div>";
    }).join("");
    const runBtn = isRunning ? '<button class="btn btn-secondary btn-sm" disabled>Running...</button>' : \`<button class="btn btn-success btn-sm" onclick="handleRunJobLegacy('\` + jobId + \`')">&#9654; Run Job</button>\`;
    const jobInfo = job.name ? "<p><strong>Job:</strong> " + escapeHtml(job.name) + "</p><p><strong>Stage:</strong> " + escapeHtml(job.stage || "unknown") + '</p><p><strong>Status:</strong> <span class="' + getStatusBadgeClass(job.status) + '">' + (job.status || "unknown") + "</span></p>" + (job.duration ? "<p><strong>Duration:</strong> " + formatDuration(job.duration) + "</p>" : "") : "";
    const artifactsSection = artifacts.length > 0 ? '<div class="card"><div class="card-header"><h2>Artifacts</h2><span class="text-muted">' + artifacts.length + ' files</span></div><div class="card-body">' + renderArtifacts(artifacts, jobId) + "</div></div>" : "";
    return '<a href="javascript:history.back()" class="back-link">&larr; Back</a>' + (jobInfo ? '<div class="card"><div class="card-header"><div class="flex-between" style="width:100%"><h2>Job Details</h2>' + runBtn + '</div></div><div class="card-body">' + jobInfo + "</div></div>" : "") + artifactsSection + '<div class="card"><div class="card-header"><h2>Job Logs</h2><span class="text-muted">' + logs.length + ' lines</span></div><div class="card-body"><div class="log-viewer">' + (lines || '<div class="text-muted">No logs</div>') + "</div></div></div>";
  }
  function updateYamlView() {
    const sourceBtn = document.getElementById("yaml-source-btn");
    const renderedBtn = document.getElementById("yaml-rendered-btn");
    const yamlViewer = document.querySelector(".yaml-viewer");
    const lineCountSpan = document.getElementById("yaml-line-count");
    const titleSpan = document.getElementById("yaml-title");
    if (sourceBtn) sourceBtn.className = "btn" + (yamlViewMode === "source" ? " active" : "");
    if (renderedBtn) renderedBtn.className = "btn" + (yamlViewMode === "rendered" ? " active" : "");
    const data = yamlViewMode === "source" ? cachedSourceYaml : cachedExpandedYaml;
    if (yamlViewer && data) {
      if (data.exists && data.content) {
        yamlViewer.innerHTML = highlightYaml(data.content);
        if (lineCountSpan) lineCountSpan.textContent = data.content.split("\\n").length + " lines";
        if (titleSpan) titleSpan.textContent = yamlViewMode === "source" ? ".gitlab-ci.yml" : "expanded-gitlab-ci.yml";
      } else {
        yamlViewer.innerHTML = '<div class="text-muted" style="padding:1rem">' + (data.error || "Not available") + "</div>";
        if (lineCountSpan) lineCountSpan.textContent = "";
      }
    }
  }
  function renderYaml(data, expandedData, config) {
    cachedSourceYaml = data;
    cachedExpandedYaml = expandedData;
    if (!data.exists) {
      return '<div class="card"><div class="empty-state"><div class="empty-state-icon">\\u{1F4C4}</div><div>No .gitlab-ci.yml found</div><div class="text-muted">Create a .gitlab-ci.yml file in the project root</div></div></div>';
    }
    const displayData = yamlViewMode === "source" ? data : expandedData.exists ? expandedData : data;
    const highlighted = highlightYaml(displayData.content || "");
    const lineCount = (displayData.content || "").split("\\n").length;
    const title = yamlViewMode === "source" ? ".gitlab-ci.yml" : "expanded-gitlab-ci.yml";
    const sourceActive = yamlViewMode === "source" ? " active" : "";
    const renderedActive = yamlViewMode === "rendered" ? " active" : "";
    const renderedDisabled = !expandedData.exists ? ' disabled title="Run a pipeline first to generate expanded YAML"' : "";
    return '<div class="card"><div class="card-header"><div><h2 id="yaml-title">' + title + '</h2><div class="cwd-info">' + escapeHtml(config.cwd) + '</div></div><div class="action-bar"><div class="btn-group"><button id="yaml-source-btn" class="btn' + sourceActive + \`" onclick="toggleYamlView('source')">Source</button><button id="yaml-rendered-btn" class="btn\` + renderedActive + '"' + renderedDisabled + \` onclick="toggleYamlView('rendered')">Rendered</button></div><span id="yaml-line-count" class="text-muted">\` + lineCount + ' lines</span></div></div><div class="card-body" style="padding:0"><div class="yaml-viewer">' + highlighted + "</div></div></div>";
  }
  async function refreshPipelineView() {
    const hash = location.hash.slice(1);
    if (!hash.startsWith("/pipeline/")) return;
    const pipelineId = hash.split("/")[2];
    const [data, status, structure] = await Promise.all([fetchPipeline(pipelineId), fetchPipelineStatus(), fetchPipelineStructure()]);
    pipelineRunning = status && status.running;
    const p = data.pipeline;
    const enrichedJobs = (data.jobs || []).map((job) => {
      const structJob = structure?.jobs?.find((sj) => sj.name === job.name);
      return {
        ...job,
        isManual: structJob?.isManual || false,
        description: structJob?.description
      };
    });
    const enrichedData = { ...data, jobs: enrichedJobs };
    const jobs = enrichedJobs;
    const logPanelExists = document.getElementById("live-log-viewer") !== null;
    const needsLogPanel = selectedJobId !== null;
    if (needsLogPanel !== logPanelExists) {
      let selectedJob = null;
      let logData = null;
      if (selectedJobId) {
        selectedJob = jobs.find((j) => j.id === selectedJobId) || null;
        if (selectedJob) {
          logData = await fetchJobLogs(selectedJobId);
        }
      }
      const root = document.getElementById("app-root");
      if (root) {
        root.innerHTML = renderPipelineDetail(enrichedData, selectedJob, logData, structure);
        renderedLogCount = logData && logData.logs ? logData.logs.length : 0;
        scheduleDependencyLinesDraw();
        if (resourceChart) {
          resourceChart.destroy();
          resourceChart = null;
        }
        initResourceChart();
        if (data.resourceMonitor && data.resourceMonitor.containerStats) {
          updateResourceChart(data.resourceMonitor.containerStats);
        }
        if (logAutoScroll && selectedJobId) {
          const viewer = document.getElementById("live-log-viewer");
          if (viewer) viewer.scrollTop = viewer.scrollHeight;
        }
      }
      return;
    }
    const pipelineStatus = document.getElementById("pipeline-status");
    if (pipelineStatus) {
      pipelineStatus.className = getStatusBadgeClass(p.status);
      pipelineStatus.textContent = p.status;
      const cancelBtn = pipelineStatus.parentElement?.querySelector(".btn-danger");
      if (p.status === "running" && !cancelBtn) {
        pipelineStatus.insertAdjacentHTML("afterend", '<button class="btn btn-danger btn-sm" onclick="handleCancelPipeline()">Cancel</button>');
      } else if (p.status !== "running" && cancelBtn) {
        cancelBtn.remove();
      }
    }
    const pipelineDuration = document.getElementById("pipeline-duration");
    if (pipelineDuration) {
      pipelineDuration.textContent = "Duration: " + formatDuration(p.duration);
    }
    const pipelineDag = document.getElementById("pipeline-dag");
    if (pipelineDag) {
      const dagJobs = pipelineDag.querySelectorAll(".dag-job");
      const jobsChanged = dagJobs.length !== jobs.length;
      if (!jobsChanged) {
        jobs.forEach((job) => {
          const jobEl = pipelineDag.querySelector('.dag-job[data-job-id="' + job.id + '"]');
          if (jobEl) {
            const manualClass = job.isManual ? " manual" : "";
            const selectedClass = job.id === selectedJobId ? " selected" : "";
            jobEl.className = "dag-job status-" + job.status + selectedClass + manualClass;
            const iconEl = jobEl.querySelector(".dag-job-icon");
            if (iconEl) {
              iconEl.textContent = getStatusIcon(job.status);
            }
            const tooltipInfo = jobEl.querySelector(".dag-job-tooltip-info");
            if (tooltipInfo) {
              tooltipInfo.textContent = job.status + (job.duration ? " \\u2022 " + formatDuration(job.duration) : "");
            }
          }
        });
      } else {
        pipelineDag.innerHTML = renderDagVisualization(jobs, selectedJobId, null, structure?.stages);
        scheduleDependencyLinesDraw();
      }
    }
    if (selectedJobId) {
      const selectedJob = jobs.find((j) => j.id === selectedJobId);
      if (selectedJob) {
        const logData = await fetchJobLogs(selectedJobId);
        const logs = logData.logs || [];
        const selection = window.getSelection();
        const hasSelection = selection && selection.toString().length > 0;
        if (!hasSelection) {
          const jobHeader = document.getElementById("job-header");
          if (jobHeader) {
            jobHeader.innerHTML = escapeHtml(selectedJob.name) + ' <span class="' + getStatusBadgeClass(selectedJob.status) + '">' + selectedJob.status + "</span>";
          }
        }
        const runBtn = document.getElementById("run-job-btn");
        if (runBtn) {
          runBtn.disabled = pipelineRunning;
        }
        const viewer = document.getElementById("live-log-viewer");
        if (viewer) {
          const wasAtBottom = viewer.scrollHeight - viewer.scrollTop - viewer.clientHeight < 50;
          if (!hasSelection) {
            if (renderedLogCount === 0) {
              if (logs.length > 0) {
                const allHtml = logs.map((l, i) => {
                  return '<div class="live-log-line"><span class="live-log-line-number">' + (i + 1) + '</span><span class="live-log-content">' + parseAnsiColors(l.content) + "</span></div>";
                }).join("");
                viewer.innerHTML = allHtml;
              } else {
                viewer.innerHTML = '<div class="text-muted" style="padding:1rem">No logs yet</div>';
              }
              renderedLogCount = logs.length;
            } else if (logs.length > renderedLogCount) {
              const newLogs = logs.slice(renderedLogCount);
              const newHtml = newLogs.map((l, i) => {
                const lineNum = renderedLogCount + i + 1;
                return '<div class="live-log-line"><span class="live-log-line-number">' + lineNum + '</span><span class="live-log-content">' + parseAnsiColors(l.content) + "</span></div>";
              }).join("");
              viewer.insertAdjacentHTML("beforeend", newHtml);
              renderedLogCount = logs.length;
            }
          }
          if (logAutoScroll && wasAtBottom && !hasSelection) {
            viewer.scrollTop = viewer.scrollHeight;
          }
        }
        if (!hasSelection) {
          const logCount = document.getElementById("log-count");
          if (logCount) {
            const totalLogs = logData.total || logs.length;
            const reachedLimit = logs.length < totalLogs;
            logCount.textContent = logs.length + " lines" + (reachedLimit ? " (reached limit of " + logs.length + ", total: " + totalLogs + ")" : "");
          }
        }
      }
    }
    if (data.resourceMonitor && data.resourceMonitor.containerStats) {
      updateResourceChart(data.resourceMonitor.containerStats);
    }
  }
  window.handleRunPipeline = async () => {
    try {
      const result = await runPipeline();
      if (result.success) {
        pipelineRunning = true;
        router();
      } else {
        alert("Failed to start pipeline: " + (result.error || "Unknown error"));
      }
    } catch (e) {
      console.error("Error running pipeline:", e);
      alert("Error: " + e.message);
    }
  };
  window.closeManualDialog = closeManualDialog;
  window.confirmManualJobs = confirmManualJobs;
  window.selectAllManualJobs = selectAllManualJobs;
  window.selectNoManualJobs = selectNoManualJobs;
  window.handleCancelPipeline = async () => {
    if (!confirm("Cancel the running pipeline?")) return;
    try {
      const result = await cancelPipeline();
      if (result.success) {
        pipelineRunning = false;
        router();
      }
    } catch (e) {
      alert("Error: " + e.message);
    }
  };
  window.handleRunJob = async (jobId, jobName) => {
    const jobEl = document.querySelector('.dag-job[data-job-id="' + jobId + '"]');
    if (jobEl) {
      jobEl.className = jobEl.className.replace(/status-[a-zA-Z0-9_]+/, "status-running");
      const iconEl = jobEl.querySelector(".dag-job-icon");
      if (iconEl) iconEl.textContent = "\\u25C9";
      const tooltipInfo = jobEl.querySelector(".dag-job-tooltip-info");
      if (tooltipInfo) tooltipInfo.textContent = "running";
    }
    const jobHeader = document.getElementById("job-header");
    if (jobHeader && selectedJobId === jobId) {
      jobHeader.innerHTML = escapeHtml(jobName) + ' <span class="badge badge-running">running</span>';
    }
    const runBtn = document.getElementById("run-job-btn");
    if (runBtn) runBtn.disabled = true;
    try {
      const result = await runSingleJob(jobId);
      if (result.success) {
        pipelineRunning = true;
      } else {
        alert("Failed to run job: " + (result.error || "Unknown error"));
        router();
      }
    } catch (e) {
      alert("Error: " + e.message);
      router();
    }
  };
  window.handleRunJobLegacy = async (jobId) => {
    try {
      const result = await runSingleJob(jobId);
      if (result.success) {
        alert("Job started: " + result.job);
        router();
      } else {
        alert("Failed to start job: " + (result.error || "Unknown error"));
      }
    } catch (e) {
      alert("Error: " + e.message);
    }
  };
  window.handleTriggerManualJob = async (jobId, _jobName) => {
    try {
      const result = await apiClient.runJob(jobId);
      if (result.success) {
        const jobEl = document.querySelector(\`[data-job-id="\${jobId}"]\`);
        if (jobEl) {
          jobEl.className = jobEl.className.replace(/status-[a-zA-Z0-9_]+/, "status-running");
          const iconEl = jobEl.querySelector(".dag-job-icon");
          if (iconEl) iconEl.textContent = "\\u25B6";
        }
      } else {
        alert("Failed to trigger manual job: " + (result.error || "Unknown error"));
      }
    } catch (e) {
      console.error("Error triggering manual job:", e);
      alert("Error: " + e.message);
    }
  };
  window.handleRunStage = async (stageName) => {
    const allJobs = document.querySelectorAll(".dag-job");
    allJobs.forEach((jobEl) => {
      const stageEl = jobEl.closest(".dag-stage");
      if (stageEl) {
        const stageHeader = stageEl.querySelector(".dag-stage-header span");
        if (stageHeader && stageHeader.textContent?.toLowerCase() === stageName.toLowerCase()) {
          const jobName = jobEl.getAttribute("data-job-name");
          const jobId = jobEl.getAttribute("data-job-id");
          if (jobName && !queuedJobs.some((j) => j.name === jobName)) {
            queuedJobs.push({ id: jobId || "", name: jobName });
          }
          jobEl.className = jobEl.className.replace(/status-[a-zA-Z0-9_]+/, "status-pending");
          const iconEl = jobEl.querySelector(".dag-job-icon");
          if (iconEl) iconEl.textContent = "\\u25CE";
          const tooltipInfo = jobEl.querySelector(".dag-job-tooltip-info");
          if (tooltipInfo) tooltipInfo.textContent = "queued";
        }
      }
    });
    if (!pipelineRunning) {
      setTimeout(processJobQueue, 300);
    }
  };
  async function processJobQueue() {
    if (pipelineRunning || queuedJobs.length === 0) return;
    const jobsToRun = queuedJobs.map((j) => j.name);
    queuedJobs = [];
    try {
      const result = await runPipeline(jobsToRun);
      if (result.success) {
        pipelineRunning = true;
        router();
      } else {
        alert("Failed to run jobs: " + (result.error || "Unknown error"));
        router();
      }
    } catch (e) {
      alert("Error: " + e.message);
      router();
    }
  }
  window.handleLogScroll = () => {
    const viewer = document.getElementById("live-log-viewer");
    if (viewer) {
      const atBottom = viewer.scrollHeight - viewer.scrollTop - viewer.clientHeight < 50;
      logAutoScroll = atBottom;
    }
  };
  window.showPipeline = (id) => {
    location.hash = "/pipeline/" + id;
  };
  window.showJobLogs = (id) => {
    location.hash = "/job/" + id + "/logs";
  };
  window.selectJob = async (jobId) => {
    const thisSelection = ++selectJobCounter;
    selectedJobId = jobId;
    logAutoScroll = true;
    renderedLogCount = 0;
    if (logRefreshInterval) {
      clearInterval(logRefreshInterval);
      logRefreshInterval = null;
    }
    await refreshPipelineView();
    if (thisSelection !== selectJobCounter) return;
    logRefreshInterval = window.setInterval(async () => {
      if (selectedJobId && thisSelection === selectJobCounter) {
        await refreshPipelineView();
        if (logAutoScroll) {
          const viewer = document.getElementById("live-log-viewer");
          if (viewer) {
            viewer.scrollTop = viewer.scrollHeight;
          }
        }
      } else if (thisSelection !== selectJobCounter) {
        clearInterval(logRefreshInterval);
      }
    }, 1e3);
  };
  window.closeLogPanel = () => {
    selectedJobId = null;
    renderedLogCount = 0;
    if (logRefreshInterval) {
      clearInterval(logRefreshInterval);
      logRefreshInterval = null;
    }
    refreshPipelineView();
  };
  window.toggleResourceMonitor = toggleResourceMonitor;
  window.toggleTheme = toggleTheme;
  window.toggleYamlView = (mode) => {
    yamlViewMode = mode;
    updateYamlView();
  };
  async function router() {
    const thisRoute = ++routerCounter;
    const root = document.getElementById("app-root");
    if (!root) return;
    const hash = location.hash.slice(1) || "/";
    updateNav(hash);
    root.innerHTML = '<div class="loading"><div class="spinner"></div></div>';
    const container = document.querySelector(".app-main .container");
    if (container && !hash.startsWith("/pipeline/")) {
      container.classList.remove("full-width");
    }
    if (refreshInterval) {
      clearInterval(refreshInterval);
      refreshInterval = null;
    }
    try {
      if (hash === "/yaml") {
        const [data, expandedData, config] = await Promise.all([fetchYaml(), fetchExpandedYaml(), fetchConfig()]);
        root.innerHTML = renderYaml(data, expandedData, config);
      } else if (hash.startsWith("/pipeline/")) {
        const id = hash.split("/")[2];
        if (logRefreshInterval) {
          clearInterval(logRefreshInterval);
          logRefreshInterval = null;
        }
        selectedJobId = null;
        statsHistory = {};
        jobColorIndex = 0;
        jobColorMap = {};
        if (resourceChart) {
          resourceChart.destroy();
          resourceChart = null;
        }
        const [data, structure] = await Promise.all([fetchPipeline(id), fetchPipelineStructure()]);
        if (thisRoute !== routerCounter) return;
        const enrichedJobs = (data.jobs || []).map((job) => {
          const structJob = structure?.jobs?.find((sj) => sj.name === job.name);
          return {
            ...job,
            isManual: structJob?.isManual || false,
            description: structJob?.description
          };
        });
        const enrichedData = { ...data, jobs: enrichedJobs };
        root.innerHTML = renderPipelineDetail(enrichedData, null, null, structure);
        scheduleDependencyLinesDraw();
        initResourceChart();
        if (data.resourceMonitor && data.resourceMonitor.containerStats) {
          updateResourceChart(data.resourceMonitor.containerStats);
        }
        refreshInterval = window.setInterval(async () => {
          try {
            if (thisRoute !== routerCounter) {
              clearInterval(refreshInterval);
              return;
            }
            if (!selectedJobId && location.hash.slice(1).startsWith("/pipeline/")) {
              await refreshPipelineView();
            }
          } catch {
          }
        }, 2e3);
      } else if (hash.startsWith("/job/") && hash.endsWith("/logs")) {
        const id = hash.split("/")[2];
        const [logsData, artifactsData, jobData, runStatus] = await Promise.all([
          fetchJobLogs(id),
          fetchJobArtifacts(id),
          fetchJob(id),
          fetchPipelineStatus()
        ]);
        const combined = {
          logs: logsData.logs,
          artifacts: artifactsData.artifacts,
          job: jobData.job
        };
        root.innerHTML = renderJobLogs(combined, id, runStatus);
      } else {
        const [pipelines, status, structure] = await Promise.all([fetchPipelines(), fetchPipelineStatus(), fetchPipelineStructure()]);
        if (thisRoute !== routerCounter) return;
        let recentJobs = [];
        if (pipelines.length > 0) {
          try {
            const recentPipeline = await fetchPipeline(pipelines[0].id);
            recentJobs = recentPipeline.jobs || [];
          } catch {
          }
        }
        if (thisRoute !== routerCounter) return;
        root.innerHTML = renderPipelineList(pipelines, status, structure, recentJobs);
        scheduleDependencyLinesDraw();
        refreshInterval = window.setInterval(async () => {
          try {
            if (thisRoute !== routerCounter) {
              clearInterval(refreshInterval);
              return;
            }
            const [newPipelines, newStatus, newStructure] = await Promise.all([fetchPipelines(), fetchPipelineStatus(), fetchPipelineStructure()]);
            let newRecentJobs = [];
            if (newPipelines.length > 0) {
              try {
                const recentPipeline = await fetchPipeline(newPipelines[0].id);
                newRecentJobs = recentPipeline.jobs || [];
              } catch {
              }
            }
            if (location.hash.slice(1) === "/" || location.hash === "") {
              updatePipelineListContent(newPipelines, newStatus, newStructure, newRecentJobs);
            }
          } catch {
          }
        }, 2e3);
      }
    } catch (e) {
      root.innerHTML = '<div class="card"><div class="empty-state"><div class="empty-state-icon">&#9888;</div><div>Error loading data</div><div class="text-muted">' + escapeHtml(e.message) + "</div></div></div>";
    }
  }
  document.addEventListener("DOMContentLoaded", () => {
    window.addEventListener("hashchange", router);
    updateThemeIcon(getStoredTheme());
    router();
  });
})();

    </script>
</body>
</html>`;
